#!/usr/bin/env bash
# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
# Release helper for the SCAMP workspace.
#
# Assumes you've already pushed a tagged commit (or otherwise triggered the
# `Build wheels` workflow) on the scamp repo so that GitHub Actions has built
# the cross-platform wheels + sdist.
#
# Walks through:
#   1. download scamp's CI artifacts into scamp/dist/
#   2. build the intel-mac wheel locally via build_macos_12_wheel.sh
#   3. build sdist + wheel for each pure-python sibling package
#   4. twine upload for each package, asking before each one
#
# Each significant step prints the command(s) it's about to run and asks for
# confirmation.

set -euo pipefail

WORKSPACE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCAMP_DIR="$WORKSPACE_DIR/scamp"
PURE_PKGS=(clockblocks expenvelope pymusicxml scamp_extensions)
# Dependency order: expenvelope <- clockblocks <- scamp <- scamp_extensions
# (pymusicxml is independent, but must precede scamp, which requires it).
UPLOAD_ORDER=(expenvelope pymusicxml clockblocks scamp scamp_extensions)
GH_REPO="MarcTheSpark/scamp"

# ---------------------------------------------------------------- helpers ----

c_bold=$(printf '\033[1m')
c_dim=$(printf '\033[2m')
c_cyan=$(printf '\033[36m')
c_yellow=$(printf '\033[33m')
c_reset=$(printf '\033[0m')

heading() {
    printf '\n%s== %s ==%s\n' "$c_bold" "$*" "$c_reset"
}

show_cmd() {
    printf '%s$ %s%s\n' "$c_cyan" "$*" "$c_reset"
}

confirm() {
    # confirm "Question?"  -> returns 0 if yes, 1 if no
    local prompt="$1"
    local reply
    while true; do
        printf '%s%s [y/n/q]%s ' "$c_yellow" "$prompt" "$c_reset"
        read -r reply
        case "$reply" in
            y|Y|yes) return 0 ;;
            n|N|no)  return 1 ;;
            q|Q|quit) echo "aborting."; exit 0 ;;
            *) echo "  please answer y, n, or q to quit." ;;
        esac
    done
}

run_step() {
    # run_step "Description" "shell command string"
    local desc="$1"; shift
    local cmd="$1"; shift
    heading "$desc"
    show_cmd "$cmd"
    if confirm "Run this?"; then
        bash -c "$cmd"
    else
        echo "  ${c_dim}skipped.${c_reset}"
        return 1
    fi
}

require() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "ERROR: '$1' not found on PATH. $2" >&2
        exit 1
    fi
}

# ------------------------------------------------------------ pre-flight ----

require python3 "Need Python 3.12+ to drive the builds."
require twine   "Install with: pip install twine"
if ! python3 -c 'import build' 2>/dev/null; then
    echo "ERROR: the 'build' package is not installed. Install with: pip install build" >&2
    exit 1
fi
require gh "Install the GitHub CLI from https://cli.github.com/ (used to fetch CI artifacts)."

heading "SCAMP workspace release"
echo "Workspace: $WORKSPACE_DIR"
echo "Scamp pkg: $SCAMP_DIR"
echo "Pure-py:   ${PURE_PKGS[*]}"
echo "GH repo:   $GH_REPO"

# --------------------------------------------------- 1. download CI artifacts

heading "Step 1: download CI wheels + sdist into scamp/dist"
echo "Latest 'Build wheels' runs on $GH_REPO:"
show_cmd "gh run list --repo $GH_REPO --workflow build-wheels.yml --limit 5"
gh run list --repo "$GH_REPO" --workflow build-wheels.yml --limit 5 || true
echo
printf '%sEnter the run ID to download (blank = latest successful):%s ' "$c_yellow" "$c_reset"
read -r RUN_ID

if [[ -z "$RUN_ID" ]]; then
    RUN_ID=$(gh run list --repo "$GH_REPO" --workflow build-wheels.yml \
                --status success --limit 1 --json databaseId -q '.[0].databaseId')
    echo "Using latest successful run: $RUN_ID"
fi

DOWNLOAD_TMP=$(mktemp -d)
DL_CMD="gh run download $RUN_ID --repo $GH_REPO --dir '$DOWNLOAD_TMP'"
heading "Step 1a: fetch artifacts from run $RUN_ID"
show_cmd "$DL_CMD"
show_cmd "mkdir -p '$SCAMP_DIR/dist' && find '$DOWNLOAD_TMP' -type f \\( -name '*.whl' -o -name '*.tar.gz' \\) -exec cp {} '$SCAMP_DIR/dist/' \\;"
if confirm "Download and copy into scamp/dist/?"; then
    bash -c "$DL_CMD"
    mkdir -p "$SCAMP_DIR/dist"
    find "$DOWNLOAD_TMP" -type f \( -name '*.whl' -o -name '*.tar.gz' \) -exec cp -v {} "$SCAMP_DIR/dist/" \;
    rm -rf "$DOWNLOAD_TMP"
    echo
    echo "Contents of $SCAMP_DIR/dist after download:"
    ls -1 "$SCAMP_DIR/dist"
else
    echo "  skipped CI artifact download. Existing scamp/dist contents will be used."
fi

# ------------------------------------------- 2. build the intel-mac wheel ----

run_step "Step 2: build intel-mac (macosx_12_0_x86_64) wheel locally" \
    "cd '$SCAMP_DIR' && bash scripts/wheel_building/build_macos_12_wheel.sh" || true

# --------------------------------- 3. build pure-python wheels + sdists ------

heading "Step 3: build sdist + wheel for each pure-python package"
echo "Each package builds with: python -m build  (produces both .whl and .tar.gz in <pkg>/dist/)"

for pkg in "${PURE_PKGS[@]}"; do
    pkg_dir="$WORKSPACE_DIR/$pkg"
    if [[ ! -d "$pkg_dir" ]]; then
        echo "  ${c_dim}$pkg_dir not found, skipping.${c_reset}"
        continue
    fi
    run_step "build $pkg" \
        "cd '$pkg_dir' && rm -rf dist build *.egg-info src/*.egg-info 2>/dev/null; python -m build" \
        || true
done

# -------------------------------------------- 4. twine upload each package ---

heading "Step 4: twine upload"
echo "Uploads will be done one package at a time. Confirm each."
echo "(If you want to test first, you can edit the script to add --repository testpypi.)"

upload_pkg() {
    local name="$1" dir="$2"
    if [[ ! -d "$dir/dist" ]]; then
        echo "  ${c_dim}$dir/dist does not exist, skipping $name.${c_reset}"
        return
    fi
    heading "Upload: $name"
    echo "Files in $dir/dist:"
    ls -1 "$dir/dist"
    run_step "twine upload $name" \
        "cd '$dir' && twine check dist/* && twine upload dist/*" \
        || true
}

# Upload in dependency order, so a package is never on PyPI before something it
# requires. Otherwise `pip install scamp` fails for anyone who tries during the
# window between scamp landing and its dependencies following.
for pkg in "${UPLOAD_ORDER[@]}"; do
    if [[ "$pkg" == scamp ]]; then
        upload_pkg scamp "$SCAMP_DIR"
    else
        upload_pkg "$pkg" "$WORKSPACE_DIR/$pkg"
    fi
done

heading "Done."
