#!/usr/bin/env bash
# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
# Release helper for the SCAMP workspace.
#
# Assumes each package's version is bumped, committed, tagged (vX.Y.Z), and the
# tags pushed. scamp's cross-platform wheels come from the `Build wheels` GitHub
# Actions workflow; because that workflow's test-install pulls scamp's deps from
# PyPI, the deps are uploaded (step 2) before scamp's wheels are fetched (step 3),
# and the script can trigger a fresh wheel run once they're up.
#
# Walks through:
#   1. build sdist + wheel for each pure-python sibling package
#   2. twine upload scamp's dependencies to PyPI (they must precede scamp's CI)
#   3. fetch scamp's CI wheels into scamp/dist/, and build the intel-mac wheel
#   4. twine upload scamp
#   5. twine upload scamp_extensions
#   6. publish a GitHub release for each package (dry run, then confirm)
#
# Each significant step prints the command(s) it's about to run and asks for
# confirmation.

set -euo pipefail

WORKSPACE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCAMP_DIR="$WORKSPACE_DIR/scamp"
PURE_PKGS=(clockblocks expenvelope pymusicxml scamp_extensions)   # built locally with python -m build
# Full dependency order: expenvelope <- clockblocks <- scamp <- scamp_extensions
# (pymusicxml is independent but must precede scamp, which requires it).
UPLOAD_ORDER=(expenvelope pymusicxml clockblocks scamp scamp_extensions)
# scamp's pure-python deps, uploaded to PyPI BEFORE scamp's wheels are fetched:
# scamp's CI test-install pulls them from PyPI, so a scamp release that bumps
# them builds green only once they're published.
DEP_UPLOAD_ORDER=(expenvelope pymusicxml clockblocks)
GH_REPO="MarcTheSpark/scamp"

# ---------------------------------------------------------------- helpers ----

c_bold=$(printf '\033[1m')
c_dim=$(printf '\033[2m')
c_cyan=$(printf '\033[36m')
c_yellow=$(printf '\033[33m')
c_reset=$(printf '\033[0m')

heading() {
    printf '\n%s== %s ==%s\n' "$c_bold" "$*" "$c_reset"
}

show_cmd() {
    printf '%s$ %s%s\n' "$c_cyan" "$*" "$c_reset"
}

confirm() {
    # confirm "Question?"  -> returns 0 if yes, 1 if no
    local prompt="$1"
    local reply
    while true; do
        printf '%s%s [y/n/q]%s ' "$c_yellow" "$prompt" "$c_reset"
        read -r reply
        case "$reply" in
            y|Y|yes) return 0 ;;
            n|N|no)  return 1 ;;
            q|Q|quit) echo "aborting."; exit 0 ;;
            *) echo "  please answer y, n, or q to quit." ;;
        esac
    done
}

run_step() {
    # run_step "Description" "shell command string"
    local desc="$1"; shift
    local cmd="$1"; shift
    heading "$desc"
    show_cmd "$cmd"
    if confirm "Run this?"; then
        bash -c "$cmd"
    else
        echo "  ${c_dim}skipped.${c_reset}"
        return 1
    fi
}

require() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "ERROR: '$1' not found on PATH. $2" >&2
        exit 1
    fi
}

upload_pkg() {
    local name="$1" dir="$2"
    if [[ ! -d "$dir/dist" ]]; then
        echo "  ${c_dim}$dir/dist does not exist, skipping $name.${c_reset}"
        return
    fi
    heading "Upload: $name"
    echo "Files in $dir/dist:"
    ls -1 "$dir/dist"
    run_step "twine upload $name" \
        "cd '$dir' && twine check dist/* && twine upload dist/*" \
        || true
}

publish_gh_release() {
    local name="$1" dir="$2"
    local script="$dir/scripts/publish_github_release.py"
    if [[ ! -f "$script" ]]; then
        echo "  ${c_dim}$name has no publish_github_release.py, skipping.${c_reset}"
        return
    fi
    local version tag rel
    if ! version=$(python3 -c "import tomllib; print(tomllib.load(open('$dir/pyproject.toml','rb'))['project']['version'])"); then
        echo "  ${c_dim}could not read $name's version, skipping.${c_reset}"
        return
    fi
    tag="v$version"
    rel="${script#"$WORKSPACE_DIR"/}"

    heading "Publish $name $tag as a GitHub release"
    show_cmd "python3 $rel $tag --dry-run"
    if ! python3 "$script" "$tag" --dry-run; then
        echo "  ${c_dim}dry run failed for $name — skipping (check its tag, changelog, and dist/).${c_reset}"
        return
    fi
    if confirm "Publish $name $tag to GitHub now?"; then
        show_cmd "python3 $rel $tag"
        python3 "$script" "$tag" || echo "  ${c_dim}publish failed for $name (already released?).${c_reset}"
    else
        echo "  ${c_dim}skipped $name.${c_reset}"
    fi
}

# ------------------------------------------------------------ pre-flight ----

require python3 "Need Python 3.12+ to drive the builds."
require twine   "Install with: pip install twine"
if ! python3 -c 'import build' 2>/dev/null; then
    echo "ERROR: the 'build' package is not installed. Install with: pip install build" >&2
    exit 1
fi
require gh "Install the GitHub CLI from https://cli.github.com/ (used to fetch CI artifacts)."

heading "SCAMP workspace release"
echo "Workspace: $WORKSPACE_DIR"
echo "Scamp pkg: $SCAMP_DIR"
echo "Pure-py:   ${PURE_PKGS[*]}"
echo "GH repo:   $GH_REPO"
echo "(To test uploads first, edit the twine commands to add --repository testpypi.)"

# --------------------------------- 1. build pure-python wheels + sdists ------

heading "Step 1: build sdist + wheel for each pure-python package"
echo "Each package builds with: python -m build  (produces both .whl and .tar.gz in <pkg>/dist/)"

for pkg in "${PURE_PKGS[@]}"; do
    pkg_dir="$WORKSPACE_DIR/$pkg"
    if [[ ! -d "$pkg_dir" ]]; then
        echo "  ${c_dim}$pkg_dir not found, skipping.${c_reset}"
        continue
    fi
    run_step "build $pkg" \
        "cd '$pkg_dir' && rm -rf dist build *.egg-info src/*.egg-info 2>/dev/null; python -m build" \
        || true
done

# ------------------------- 2. upload scamp's dependencies to PyPI ------------

heading "Step 2: upload scamp's dependencies to PyPI"
echo "These land before scamp's wheels are fetched: scamp's CI test-install pulls them"
echo "from PyPI, so its 'Build wheels' run only passes once they're published."

for pkg in "${DEP_UPLOAD_ORDER[@]}"; do
    upload_pkg "$pkg" "$WORKSPACE_DIR/$pkg"
done

# --------------------------- 3. fetch scamp's wheels from CI -----------------

SCAMP_VERSION=$(python3 -c "import tomllib; print(tomllib.load(open('$SCAMP_DIR/pyproject.toml','rb'))['project']['version'])")

heading "Step 3: fetch scamp's wheels from CI"
echo "scamp's wheels come from the 'Build wheels' workflow (the v* tag push triggers it)."
echo "Because its test-install needs the dependencies above on PyPI, the tag's original run"
echo "may have failed. Now that the deps are up, trigger a fresh run and download that one."

if confirm "Trigger a fresh scamp 'Build wheels' run now?"; then
    show_cmd "gh workflow run build-wheels.yml --repo $GH_REPO"
    gh workflow run build-wheels.yml --repo "$GH_REPO" \
        && echo "  triggered. Watch it finish with:  gh run watch --repo $GH_REPO"
fi

echo
echo "Wait until a run for v$SCAMP_VERSION is green, then download it below."
echo "Latest 'Build wheels' runs on $GH_REPO:"
show_cmd "gh run list --repo $GH_REPO --workflow build-wheels.yml --limit 5"
gh run list --repo "$GH_REPO" --workflow build-wheels.yml --limit 5 || true
echo
printf '%sEnter the run ID to download (blank = latest successful):%s ' "$c_yellow" "$c_reset"
read -r RUN_ID

if [[ -z "$RUN_ID" ]]; then
    RUN_ID=$(gh run list --repo "$GH_REPO" --workflow build-wheels.yml \
                --status success --limit 1 --json databaseId -q '.[0].databaseId')
    echo "Using latest successful run: $RUN_ID"
fi

DOWNLOAD_TMP=$(mktemp -d)
DL_CMD="gh run download $RUN_ID --repo $GH_REPO --dir '$DOWNLOAD_TMP'"
heading "Step 3a: fetch artifacts from run $RUN_ID"
show_cmd "$DL_CMD"
show_cmd "mkdir -p '$SCAMP_DIR/dist' && find '$DOWNLOAD_TMP' -type f \\( -name '*.whl' -o -name '*.tar.gz' \\) -exec cp {} '$SCAMP_DIR/dist/' \\;"
if confirm "Download and copy into scamp/dist/?"; then
    bash -c "$DL_CMD"
    mkdir -p "$SCAMP_DIR/dist"
    find "$DOWNLOAD_TMP" -type f \( -name '*.whl' -o -name '*.tar.gz' \) -exec cp -v {} "$SCAMP_DIR/dist/" \;
    rm -rf "$DOWNLOAD_TMP"
    echo
    echo "Contents of $SCAMP_DIR/dist after download:"
    ls -1 "$SCAMP_DIR/dist"
    if ! ls "$SCAMP_DIR"/dist/*"$SCAMP_VERSION"* >/dev/null 2>&1; then
        echo "  ${c_yellow}WARNING: nothing matching v$SCAMP_VERSION in scamp/dist — did you pick the right run?${c_reset}"
    fi
else
    echo "  skipped CI artifact download. Existing scamp/dist contents will be used."
fi

run_step "Step 3b: build intel-mac (macosx_12_0_x86_64) wheel locally" \
    "cd '$SCAMP_DIR' && bash scripts/wheel_building/build_macos_12_wheel.sh" || true

# -------------------------------------- 4. upload scamp to PyPI --------------

heading "Step 4: upload scamp to PyPI"
upload_pkg scamp "$SCAMP_DIR"

# --------------------------- 5. upload scamp_extensions to PyPI --------------

heading "Step 5: upload scamp_extensions to PyPI"
echo "scamp_extensions requires scamp, so it goes up last."
upload_pkg scamp_extensions "$WORKSPACE_DIR/scamp_extensions"

# ------------------------------------------ 6. publish GitHub releases -------

heading "Step 6: publish GitHub releases"
echo "For each package: preview the release (dry run), then confirm before publishing."
echo "Notes come from the package's CHANGELOG; assets (if any) come from its dist/."

# Order doesn't matter for releases, but reuse the upload order for consistency.
for pkg in "${UPLOAD_ORDER[@]}"; do
    if [[ "$pkg" == scamp ]]; then
        publish_gh_release scamp "$SCAMP_DIR"
    else
        publish_gh_release "$pkg" "$WORKSPACE_DIR/$pkg"
    fi
done

heading "Done."
