#!/usr/bin/env bash
# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# rsync target. Real values live in a gitignored deploy.local.sh beside this
# script (copy deploy.local.sh.example and fill it in), or come from the
# environment. Nothing host-identifying is committed to the repo.
[[ -f "$SCRIPT_DIR/deploy.local.sh" ]] && source "$SCRIPT_DIR/deploy.local.sh"

USER="${SCAMP_DEPLOY_USER:?set SCAMP_DEPLOY_USER (or add it to deploy.local.sh)}"
HOST="${SCAMP_DEPLOY_HOST:?set SCAMP_DEPLOY_HOST (or add it to deploy.local.sh)}"
REMOTE_DIR="${SCAMP_DEPLOY_REMOTE_DIR:-scamp.marcevanstein.com}"

LOCAL_DIR="$SCRIPT_DIR/docs_build"

if [[ ! -d "$LOCAL_DIR" ]]; then
    echo "Local docs dir not found: $LOCAL_DIR" >&2
    exit 1
fi

rsync -avz --delete \
    --exclude='.doctrees' \
    --exclude='.dh-diag' \
    --exclude='favicon.ico' \
    --exclude='favicon.gif' \
    "$LOCAL_DIR/" \
    "$USER@$HOST:$REMOTE_DIR/"
