#!/bin/bash
# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
# Build the Sphinx docs into docs_build/ (at the workspace root). Regenerates the API .rst files
# every time; the example pages change less often, so they are rebuilt only with
# --rebuild-examples (or automatically when missing, e.g. on a fresh checkout).
set -euo pipefail

REBUILD_EXAMPLES=0
for arg in "$@"; do
    case "$arg" in
        --rebuild-examples|--rebuild_examples) REBUILD_EXAMPLES=1 ;;
        *) echo "unknown argument: $arg" >&2; exit 1 ;;
    esac
done

# Run from the package root regardless of where we were invoked from.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Remove the generated API rst + autosummary dirs so makePackageRSTs rebuilds them
# fresh. Everything else under docs/ is source; the examples/ gallery is handled below.
rm -f  docs/scamp.rst docs/clockblocks.rst docs/expenvelope.rst docs/pymusicxml.rst
rm -rf docs/scamp docs/clockblocks docs/expenvelope docs/pymusicxml docs/scamp_extensions.*

cd docs
python3 ./makePackageRSTs.py
# The example pages change rarely, so regenerate them only on request -- or
# automatically when absent (e.g. a fresh checkout), since they aren't tracked.
if [ "$REBUILD_EXAMPLES" = "1" ] || [ ! -d examples ]; then
    python3 ./build_examples_docs.py
fi

sphinx-build . ../docs_build

firefox ../docs_build/index.html
