#!/usr/bin/env bash
# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
# Regenerate the per-folder concatenated EXAMPLE bundles uploaded to the SCAMP
# AI tutor site. Each bundle is one text file per top-level examples folder,
# every source file preceded by a "=== FILE: <relative/path>" header.
# Also regenerates and copies the examples index (which is built from the
# examples' own docstrings — see scamp/examples/regenerate_index.py).
# Sources live in scamp/examples/; JunkDrawer/ is deliberately not bundled.
#
# The output under examples/ is committed on purpose — it's what the tutor
# fetches over the web, not a throwaway build product. Don't gitignore it.
#
# Run from anywhere: ./regenerate_bundles.sh
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/.." && pwd)"
srcroot="$repo/scamp/examples"
out="$here/examples"
mkdir -p "$out"

python3 "$srcroot/regenerate_index.py"

# One bundle per top-level examples folder (Tutorial and each topic); JunkDrawer excluded.
# The folder name carries spaces and '&', so the bundle file is named by a slug of it.
for d in "$srcroot"/*/; do
  name="$(basename "$d")"
  case "$name" in JunkDrawer|__pycache__) continue ;; esac
  slug="$(printf '%s' "$name" | tr 'A-Z' 'a-z' | sed -E 's/[^a-z0-9]+/_/g; s/^_//; s/_$//')"
  dest="$out/${slug}.txt"
  : > "$dest"
  find "$d" -type f \( -name '*.py' -o -name '*.scd' \) ! -path '*__pycache__*' \
    | sort | while read -r f; do
      rel="${f#"$srcroot"/}"
      printf '\n\n======================================================================\n' >> "$dest"
      printf '=== FILE: %s\n' "$rel" >> "$dest"
      printf '======================================================================\n\n' >> "$dest"
      cat "$f" >> "$dest"
    done
  count="$(grep -c '=== FILE:' "$dest" || true)"
  if [ "$count" -eq 0 ]; then          # a topic with only cross-listed examples has no scripts of its own
    rm -f "$dest"
    continue
  fi
  echo "examples/${slug}.txt -> $count files"
done

cp "$srcroot/INDEX.md" "$out/examples_index.md"
echo "examples/examples_index.md <- scamp/examples/INDEX.md"
