#!/usr/bin/env bash
# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
# Regenerate the per-package documentation bundles uploaded to the SCAMP Tutor
# Claude Project. Each bundle is one text file per package, concatenating the
# plaintext-rendered Sphinx pages, every page preceded by a "=== FILE: <path>"
# header (same format as the example bundles).
#
# Requires Sphinx + scamp (and siblings) importable in the active environment.
#
# The output under docs/ is committed on purpose — it's what the tutor fetches
# over the web, not a throwaway build product. Don't gitignore it.
#
# Run from anywhere: ./regenerate_doc_bundles.sh
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/.." && pwd)"
docs="$repo/docs"
text="$docs/build_text"

# 1. Render docs to plaintext (autodoc expanded, no HTML bulk).
sphinx-build -b text "$docs" "$text"
rm -rf "$text/.doctrees" "$text/.buildinfo"

# 2. Concatenate into one file per package (narrative tutorials fold into scamp).
mkdir -p "$here/docs"
python3 - "$text" "$here/docs" <<'PY'
import sys, pathlib
src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
order = ['scamp_extensions', 'scamp', 'clockblocks', 'expenvelope', 'pymusicxml']
def owner(rel):
    if rel.startswith('scamp_extensions'): return 'scamp_extensions'
    if rel.startswith(('scamp.', 'scamp/', 'narrative')) or rel == 'scamp.txt': return 'scamp'
    for p in ('clockblocks', 'expenvelope', 'pymusicxml'):
        if rel.startswith(p): return p
    return None
buckets = {p: [] for p in order}
for f in sorted(src.rglob('*.txt')):
    rel = f.relative_to(src).as_posix()
    if rel == 'index.txt': continue  # overview lives in instructions.txt instead
    o = owner(rel)
    if o: buckets[o].append((rel, f))
bar = '=' * 70
for pkg in order:
    dest = out / f'{pkg}_docs.txt'
    with dest.open('w') as fo:
        for rel, f in buckets[pkg]:
            fo.write(f'\n\n{bar}\n=== FILE: {rel}\n{bar}\n\n')
            fo.write(f.read_text())
    print(f'{pkg}_docs.txt <- {len(buckets[pkg])} pages ({dest.stat().st_size // 1024} KB)')
PY
