# NOTE: THIS SOURCE FILE WAS GENERATED BY CLAUDE OPUS 4.8 WITH LITTLE HUMAN OVERSIGHT
# PLEASE REVIEW THE AI POLICY AT REPOSITORY ROOT FOR MORE INFORMATION
#  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  #
#  This file is part of SCAMP (Suite for Computer-Assisted Music in Python)                      #
#  Copyright © 2020 Marc Evanstein <marc@marcevanstein.com>.                                     #
#                                                                                                #
#  This program is free software: you can redistribute it and/or modify it under the terms of    #
#  the GNU General Public License as published by the Free Software Foundation, either version   #
#  3 of the License, or (at your option) any later version.                                      #
#                                                                                                #
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;     #
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.     #
#  See the GNU General Public License for more details.                                          #
#                                                                                                #
#  You should have received a copy of the GNU General Public License along with this program.    #
#  If not, see <http://www.gnu.org/licenses/>.                                                   #
#  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  #
"""
Generate the docs "Examples" section from the example scripts across the packages.

The gallery's grouping and order come from examples.yaml via regenerate_index.build_gallery();
the example files live in each package's examples/ dir. This writes docs/examples/index.rst
(a Tutorial list, then a by-topic list), one page per topic (section headings, each listing
its examples as links), and one page per example (description, source, media, download). Topic
pages only link to examples, so a cross-listed example appears on several without duplication.
Tutorial pages sit in the Tutorial toctree; the rest are :orphan:. Each page links to its
source on the owning package's GitHub, offers a download (the .py, or a .zip when companions
are needed), and embeds captured media (audio, score images) and hand-authored videos
(example_media.toml). The JunkDrawer is left out.

Run from anywhere: python3 build_examples_docs.py
"""

import re
import shutil
import tomllib
import zipfile
import pathlib
import urllib.parse

from regenerate_index import slugify, parse_docstring, build_gallery, PACKAGES, GITHUB

DOCS_DIR = pathlib.Path(__file__).resolve().parent
OUT_DIR = DOCS_DIR / "examples"
MEDIA_DIR = DOCS_DIR / "_static" / "media"          # audio/scores, captured by render_example_media.py
MEDIA_MANIFEST_PATH = DOCS_DIR / "example_media.toml"  # hand-authored video links, media ordering


def _load_manifest():
    if MEDIA_MANIFEST_PATH.exists():
        with open(MEDIA_MANIFEST_PATH, "rb") as f:
            return tomllib.load(f)
    return {}


MEDIA_MANIFEST = _load_manifest()

LICENSE_DELIM = re.compile(r"^#\s*\++\s*#\s*$")


def source_body(path):
    """The example source with its docstring and GPL license block stripped."""
    text = path.read_text()
    text = re.sub(r'^\s*"""(.*?)"""', "", text, count=1, flags=re.DOTALL)
    lines = text.splitlines()
    delims = [i for i, ln in enumerate(lines) if LICENSE_DELIM.match(ln)]
    if len(delims) >= 2:
        del lines[delims[0]:delims[1] + 1]
    return "\n".join(lines).strip("\n")


def script_entry(path, package, lang="python"):
    """The per-script bits shown in a code box. ``rel`` is the path within the package's
    examples/ (which is also the media key, since media mirrors the topic path)."""
    summary = parse_docstring(path) if lang == "python" else None
    return {"name": path.name, "summary": summary or "", "body": source_body(path),
            "rel": path.relative_to(PACKAGES[package]), "lang": lang}


def scd_entries(paths, package):
    return [script_entry(p, package, "supercollider")
            for p in sorted(paths) if p.is_file() and p.suffix == ".scd"]


# ---- media rendering -------------------------------------------------------

def _yt_id(url):
    for marker in ("watch?v=", "youtu.be/", "embed/"):
        if marker in url:
            url = url.split(marker, 1)[1]
            break
    return re.split(r"[&?/]", url)[0]


def unit_videos(unit):
    entry = MEDIA_MANIFEST.get(unit["rel"], {})
    vids = entry.get("video", entry.get("youtube", []))
    if isinstance(vids, str):
        vids = [vids]
    return [_yt_id(v) for v in vids]


def audio_path(script):
    return (MEDIA_DIR / script["rel"]).with_suffix(".mp3")


def score_pages(script):
    """This script's captured score SVGs, grouped by score (a long verovio score split across
    pages has more than one). See render_example_media.py for the naming."""
    base = (MEDIA_DIR / script["rel"]).with_suffix("")
    prefix = base.name

    def index(p):
        m = re.match(r"^(?:-(\d+))?(?:-p(\d+))?$", p.name[len(prefix):-len(".svg")])
        score = int(m.group(1)) if m and m.group(1) else 1
        page = int(m.group(2)) if m and m.group(2) else 1
        return score, page

    scores = {}
    for p in base.parent.glob(prefix + "*.svg"):
        rest = p.name[len(prefix):]
        if rest[:1] not in (".", "-"):
            continue
        if rest.startswith(".plot"):
            continue
        score, page = index(p)
        scores.setdefault(score, []).append((page, p))
    return [[p for _, p in sorted(pages)] for _, pages in sorted(scores.items())]


def plot_images(script):
    base = (MEDIA_DIR / script["rel"]).with_suffix("")
    prefix = base.name + ".plot"

    def num(p):
        m = re.match(r"^-(\d+)$", p.name[len(prefix):-len(".svg")])
        return int(m.group(1)) if m else 1

    return sorted(base.parent.glob(prefix + "*.svg"), key=num)


def _media_url(p):
    rel = p.relative_to(MEDIA_DIR).as_posix()
    return "../_static/media/" + urllib.parse.quote(rel)


def audio_html(p):
    return (f'<div style="margin:0.6em 0"><audio controls preload="none" '
            f'src="{_media_url(p)}" style="width:100%;max-width:520px"></audio></div>')


def score_label(p, titles=None):
    """A score's title: an example_media.toml ``score_titles`` override keyed by filename,
    else the ``.title`` sidecar written at render time, else ''."""
    if titles and p.name in titles:
        return titles[p.name]
    sidecar = p.with_suffix(".title")
    return sidecar.read_text().strip() if sidecar.exists() else ""


def _score_label_html(label):
    return (f'<div style="font-weight:bold;margin:0.6em 0 0.2em">{label}</div>'
            if label else "")


def score_html(p, label=""):
    return (_score_label_html(label) +
            f'<div style="border:1px solid #ccc;padding:8px;margin:0.2em 0 0.6em;'
            f'display:inline-block;max-width:100%">'
            f'<img src="{_media_url(p)}" alt="score" '
            f'style="max-width:100%;height:auto;display:block"></div>')


def score_pager_html(pages, label=""):
    imgs = "".join(
        f'<img src="{_media_url(p)}" alt="score page {i + 1}" class="score-page" '
        f'style="max-width:100%;height:auto;'
        f'{"display:block" if i == 0 else "display:none"}">'
        for i, p in enumerate(pages))
    return (_score_label_html(label) +
            f'<div class="score-pager" tabindex="0">'
            f'<div class="score-pager-frame">{imgs}</div>'
            f'<div class="score-pager-controls">'
            f'<button type="button" class="score-pager-prev" aria-label="Previous page">'
            f'&#9664;</button>'
            f'<span class="score-pager-status">1 / {len(pages)}</span>'
            f'<button type="button" class="score-pager-next" aria-label="Next page">'
            f'&#9654;</button>'
            f'</div></div>')


def score_block_html(pages, label=""):
    return score_html(pages[0], label) if len(pages) == 1 else score_pager_html(pages, label)


def plot_html(p):
    return (f'<figure style="display:inline-block;vertical-align:top;margin:0.2em 0.4em">'
            f'<img src="{_media_url(p)}" alt="envelope plot" '
            f'style="max-width:100%;height:auto;display:block"></figure>')


def plot_gallery_html(plots):
    return ('<div style="margin:0.4em 0">'
            + "".join(plot_html(p) for p in plots) + '</div>')


def video_html(vid):
    return (f'<iframe src="https://www.youtube-nocookie.com/embed/{vid}" '
            'style="width:100%;max-width:640px;aspect-ratio:16/9;border:0;'
            'display:block;margin:0.6em 0" allowfullscreen></iframe>')


def raw_block(html):
    return [".. raw:: html", "", "   " + html, ""]


def code_block(script, caption):
    out = [f".. code-block:: {script['lang']}"]
    if caption:
        out.append(f"   :caption: {caption}")
    out.append("")
    for ln in script["body"].splitlines():
        out.append("   " + ln if ln else "")
    out.append("")
    return out


def caption_for(script, multi):
    if not multi:
        return None
    return f"{script['name']}: {script['summary']}" if script["summary"] else script["name"]


def code_caption(script, multi):
    return caption_for(script, multi) if script["lang"] == "python" else script["name"]


def order_item(token, unit, by_name, vids, multi):
    if token in ("video", "videos"):
        return [ln for v in vids for ln in raw_block(video_html(v))]
    s = by_name.get(token)
    if s is not None:
        return code_block(s, code_caption(s, multi))
    p = unit["media_dir"] / token
    if token.endswith(".mp3") and p.exists():
        return raw_block(audio_html(p))
    if token.endswith(".svg") and p.exists():
        if ".plot" in token[:-len(".svg")]:
            return raw_block(plot_html(p))
        return raw_block(score_html(p))
    return raw_block(video_html(_yt_id(token)))


def borrowed_audio(entry):
    """example_media.toml ``borrow_audio``: media-relative mp3 path(s), rendered by some other
    example, to embed here (e.g. a graph visualizing another example's audio). Missing ones are
    skipped, so a page still builds when that example hasn't been rendered."""
    borrow = entry.get("borrow_audio", [])
    rels = [borrow] if isinstance(borrow, str) else borrow
    return [MEDIA_DIR / rel for rel in rels if (MEDIA_DIR / rel).exists()]


def body_lines(unit):
    scripts, extra = unit["scripts"], unit.get("extra", [])
    multi = len(scripts) > 1
    vids = unit_videos(unit)
    entry = MEDIA_MANIFEST.get(unit["rel"], {})
    order = entry.get("order")
    if order:
        by_name = {s["name"]: s for s in scripts + extra}
        return [ln for token in order
                for ln in order_item(token, unit, by_name, vids, multi)]

    score_titles = entry.get("score_titles", {})
    out = [ln for v in vids for ln in raw_block(video_html(v))]
    for p in borrowed_audio(entry):
        out += raw_block(audio_html(p))
    for s in scripts:
        for pages in score_pages(s):
            out += raw_block(score_block_html(pages, score_label(pages[0], score_titles)))
        plots = plot_images(s)
        if plots:
            out += raw_block(plot_gallery_html(plots))
        if audio_path(s).exists():
            out += raw_block(audio_html(audio_path(s)))
        out += code_block(s, caption_for(s, multi))
    for s in extra:
        out += code_block(s, s["name"])
    return out


def companion_files(path):
    """Non-.py siblings a root-level script needs: a same-named sidecar, or a file /
    directory it references by name (e.g. leaf_loops.py -> LeafPoints/)."""
    src = path.read_text()
    out = []
    for sib in sorted(path.parent.iterdir()):
        if sib.name == path.name or "__pycache__" in sib.name:
            continue
        if sib.is_file() and sib.suffix == ".py":
            continue
        if sib.is_dir() and any(sib.rglob("*.py")):
            continue
        if sib.stem == path.stem or sib.name in src:
            out.append(sib)
    return out


# ---- units (extend the shared gallery unit with docs-page detail) ---------

def extend_unit(u):
    """Add the docs-page fields (slug name, scripts, media dir, download) to a gallery unit."""
    pkg, path, pys = u["package"], u["path"], u["py_paths"]
    relp = pathlib.PurePosixPath(u["rel"])
    u = dict(u)
    u["name"] = slugify(u["rel"][:-len(".py")] if not u["is_folder"] else u["rel"])
    u["display"] = u["rel"] + ("/" if u["is_folder"] else "")
    u["media_dir"] = MEDIA_DIR / (relp if u["is_folder"] else relp.parent)
    if u["is_folder"]:
        main = next((p for p in pys if p.stem == path.name), None)
        ordered = ([main] + [p for p in pys if p is not main]) if main else pys
        u["scripts"] = [script_entry(p, pkg) for p in ordered]
        u["extra"] = scd_entries(path.rglob("*.scd"), pkg)
        u["download"] = ("folder", path)
    else:
        u["scripts"] = [script_entry(path, pkg)]
        u["extra"] = scd_entries(companion_files(path), pkg)
        u["download"] = ("file", path)
    return u


def write_download(unit):
    dl_dir = OUT_DIR / "downloads" / unit["name"]
    dl_dir.mkdir(parents=True, exist_ok=True)
    kind, payload = unit["download"]

    if kind == "file" and not companion_files(payload):
        shutil.copyfile(payload, dl_dir / payload.name)
        target, label = f"downloads/{unit['name']}/{payload.name}", payload.name
    else:
        if kind == "folder":
            stem = payload.name
            members = [(p, p.relative_to(payload.parent).as_posix())
                       for p in sorted(payload.rglob("*"))
                       if p.is_file() and "__pycache__" not in p.parts]
        else:
            stem = payload.stem
            members = [(payload, f"{stem}/{payload.name}")]
            for c in companion_files(payload):
                if c.is_file():
                    members.append((c, f"{stem}/{c.name}"))
                else:
                    for p in sorted(c.rglob("*")):
                        if p.is_file() and "__pycache__" not in p.parts:
                            members.append((p, f"{stem}/{c.name}/{p.relative_to(c).as_posix()}"))
        with zipfile.ZipFile(dl_dir / f"{stem}.zip", "w", zipfile.ZIP_DEFLATED) as zf:
            for source, arcname in members:
                zf.write(source, arcname)
        target, label = f"downloads/{unit['name']}/{stem}.zip", f"{stem}.zip"
    return f"*Download:* :download:`{label} <{target}>`"


def github_line(unit):
    """The '*Example script/directory:*' line, linking to the source on the owning package's
    GitHub. The path is percent-encoded for the URL -- topic folders like "Notation & engraving"
    carry spaces and ampersands -- while the visible text keeps the readable path."""
    base, branch = GITHUB[unit["package"]]
    rel = unit["rel"]
    rel_url = urllib.parse.quote(str(rel))
    tree, kind = ("tree", "directory") if unit["is_folder"] else ("blob", "script")
    url = f"{base}/{tree}/{branch}/examples/{rel_url}"
    return f"*Example {kind}* ({unit['package']}): `examples/{rel} <{url}>`__"


# ---- pages ----------------------------------------------------------------

def first_sentence(text):
    text = re.sub(r"^\s*\([^)]*\)\s*", "", text)
    m = re.match(r"\s*(.+?[.!?])(\s|$)", text, re.DOTALL)
    return m.group(1).strip() if m else text.strip()


def _topic_entry(u):
    line = f"- :doc:`{u['title']} <{u['name']}>`"
    if u["summary"]:
        line += f" — {first_sentence(u['summary'])}"
    if u["needs_ext"]:
        line += " *(needs scamp_extensions)*"
    return line


def write_topic_page(topic, sections):
    """A topic page: a section heading per section, each listing its examples as links."""
    out = [topic, "=" * len(topic), ""]
    for section, units in sections.items():
        if section:
            out += ["", section, "-" * len(section), ""]
        for u in units:
            out.append(_topic_entry(u))
        out.append("")
    (OUT_DIR / f"{slugify(topic)}.rst").write_text("\n".join(out).rstrip("\n") + "\n")


def topics_line(unit, locations):
    crumbs = []
    for topic, section in locations.get(unit["key"], []):
        text = f"{topic} › {section}" if section else topic
        crumbs.append(f":doc:`{text} <{slugify(topic)}>`")
    return "*Topics:* " + ", ".join(crumbs) if crumbs else None


def write_example_page(unit, locations):
    title = unit["title"]
    orphan = not unit["is_tutorial"]
    out = ([":orphan:", ""] if orphan else []) + [
        title, "=" * len(title), "", github_line(unit), "", write_download(unit), ""]
    if unit["needs_ext"]:
        out += ["**Requires the** ``scamp_extensions`` **package** "
                "(``pip install scamp_extensions``).", ""]
    if unit["summary"]:
        out += [unit["summary"], ""]
    topics = topics_line(unit, locations)
    if topics:
        out += [topics, ""]
    out += body_lines(unit)
    (OUT_DIR / f"{unit['name']}.rst").write_text("\n".join(out) + "\n")


def write_tutorial_page(tutorial):
    out = ["Tutorial", "========", "",
           "Work through these in order for a guided tour of the framework.", ""]
    for u in tutorial:
        line = f"#. :doc:`{u['title']} <{u['name']}>`"
        if u["summary"]:
            line += f" — {first_sentence(u['summary'])}"
        out.append(line)
    out += ["", ".. toctree::", "   :hidden:", ""]
    out += [f"   {u['name']}" for u in tutorial]
    out.append("")
    (OUT_DIR / "tutorial.rst").write_text("\n".join(out) + "\n")


def write_index(topics):
    out = [
        "Examples", "========", "",
        "A gallery of the example scripts across the SCAMP packages. The **tutorial** examples",
        "are a progressively-ordered teaching set; the **by-topic** pages collect every",
        "example (tutorial and beyond) by subject.",
        "",
        ".. rubric:: Tutorial", "",
        ":doc:`Work through the tutorial <tutorial>` in order for a guided tour of the "
        "framework.", "",
        ".. rubric:: By topic", "",
        "Each topic is one page, grouping its examples under headings.", "",
    ]
    for topic, sections in topics.items():
        secs = [s for s in sections if s]
        line = f"- :doc:`{topic} <{slugify(topic)}>`"
        out.append(line + (f" — {' · '.join(secs)}" if secs else ""))
    out += ["", ".. toctree::", "   :hidden:", "", "   tutorial"]
    out += [f"   {slugify(t)}" for t in topics]
    out.append("")
    (OUT_DIR / "index.rst").write_text("\n".join(out) + "\n")


def main():
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir()
    gallery = build_gallery()
    units = {key: extend_unit(u) for key, u in gallery["units"].items()}
    topics = {
        topic: {sec: [units[u["key"]] for u in us] for sec, us in sections.items()}
        for topic, sections in gallery["topics"].items()
    }
    tutorial = [units[u["key"]] for u in gallery["tutorial"]]
    locations = gallery["locations"]

    for topic, sections in topics.items():
        write_topic_page(topic, sections)
    for unit in units.values():
        write_example_page(unit, locations)
    write_tutorial_page(tutorial)
    write_index(topics)
    print(f"docs/examples/: {len(units)} example pages, {len(topics)} topics "
          f"({len(tutorial)} tutorial)")


if __name__ == "__main__":
    main()
